num1=26
num2=3
addition=num1+num2
subtraction=num1-num2
multiplication=num1*num2
division=num1/num2
print("addition",num1+num2)
print("subtraction",num1-num2)
print("multiplication",num1*num2)
print("division",num1/num2)
